import turtle
turtle.home()

turtle.circle(100)
turtle.left(90)
turtle.penup()
turtle.forward(80)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.left(45)
turtle.forward(70)
turtle.pendown()
turtle.circle(10)
turtle.right(145)
turtle.penup()
turtle.forward(100)
turtle.pendown()
turtle.circle(10)
turtle.right(90)
turtle.penup()
turtle.forward(80)
turtle.right(45)
turtle.pendown()
turtle.forward(30)
turtle.right(45)
turtle.forward(30)
turtle.right(45)
turtle.forward(30)

input("press enter to exit")
